New Changes

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,8 @@
 #!/bin/bash
-
+# if git diff --name-only --cached | grep -q ".husky/pre-commit\|.husky/post-commit"; then
+#   echo "Error: pre-commit and post-commit files cannot be modified."
+#   exit 1
+# fi
 # Check if Husky is installed
 if ! command -v husky &> /dev/null
 then
@@ -9,7 +12,7 @@ then
     # Initialize Husky hooks if it's not already set up
     npx husky install
 else
-    echo "Husky is already installed."
+    echo "Husky is already installed Sucessfully."
 fi
 
 # Get the list of changed Apex (.cls) or LWC files
