New Changes

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -45,24 +45,17 @@ jobs:
       - name: Run SFDX Scanner on All Changed Files
         id: run-scanner
         run: |
-          # Create an empty CSV file
-          echo "Rule Name,File,Line,Category,Severity,Message" > scanner-report.csv
-
-          # Find all Apex (.cls) and LWC files and scan them
           files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
           echo "Files to scan: $files"
           if [ -n "$files" ]; then
+            # Process all files individually in a loop
             for file in $files; do
               echo "Running scanner on $file"
-              # Append results to the existing CSV file
-              sf scanner:run --target "$file" --format csv --outfile temp-scanner-report.csv
-              # Append the scanned results into scanner-report.csv
-              tail -n +2 temp-scanner-report.csv >> scanner-report.csv
+              sf scanner:run --target "$file" --format csv --outfile scanner-report.csv --category "Performance" || { echo "Scanner run failed on $file"; exit 1; }
             done
-            # Clean up the temporary file
-            rm temp-scanner-report.csv
           else
             echo "No relevant files changed."
+            touch scanner-report.csv
           fi
         env:
           SF_LAZY_LOAD_MODULES: 'true'
@@ -72,7 +65,8 @@ jobs:
       - name: Block PR merge if severity 3 violations are found
         run: |
           if [ -f scanner-report.csv ]; then
-            severity_fail_count=$(awk -F',' '{gsub(/^ *| *$/, "", $5); if($5 == "\"3\"") count++} END {print count}' scanner-report.csv)
+            # Assuming 'severity' is the third column in the CSV
+            severity_fail_count=$(awk -F',' '{gsub(/^ *| *$/, "", $2); if($2 == "\"3\"") count++} END {print count}' scanner-report.csv)
             echo "Severity 3 issues count: $severity_fail_count"
             if [ "$severity_fail_count" -gt 0 ]; then
               echo "Blocking your pull request due to severity 3 vulnerabilities found."
@@ -86,7 +80,7 @@ jobs:
           fi
 
       - name: Upload Scanner Report
-        if: always()
+        if: success()
         uses: actions/upload-artifact@v3
         with:
           name: SFDX_Code_Scan_Report
