New Changes

diff --git a/.github/workflows/delta-scan.yml b/.github/workflows/delta-scan.yml
--- a/.github/workflows/delta-scan.yml
+++ b/.github/workflows/delta-scan.yml
@@ -41,22 +41,22 @@ jobs:
             echo "No previous commit to compare to." > changed_files.txt
           fi
           cat changed_files.txt
- 
+          
       - name: Run SFDX Scanner on Changed Files
         if: success()
         run: |
-            files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
-            echo "Files to scan: $files"
-            if [ -n "$files" ]; then
-              sf scanner:run --target "$files" --engine "pmd,eslint" --format "csv" --outfile "scanner-report.csv" || { echo "Scanner run failed"; exit 1; }
-            else
-              echo "No relevant files changed."
-              touch scanner-report.csv
-            fi
+          files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
+          echo "Files to scan: $files"
+          if [ -n "$files" ]; then
+            sf scanner:run --target "$files" --format "csv" --outfile "scanner-report.csv" || { echo "Scanner run failed"; exit 1; }
+          else
+            echo "No relevant files changed."
+            touch scanner-report.csv
+          fi
         env:
-            SF_LAZY_LOAD_MODULES: 'true'
-            SF_AUTOUPDATE_DISABLE: 'true'
-            SF_DISABLE_AUTOUPDATE: 'true'
+          SF_LAZY_LOAD_MODULES: 'true'
+          SF_AUTOUPDATE_DISABLE: 'true'
+          SF_DISABLE_AUTOUPDATE: 'true'
  
       - name: Encode CSV file to Base64
         if: success()
